### PR TITLE
Release/20200402

### PR DESCRIPTION
**Pull request by FuhuXia**
This merges branch `develop` into `master`

### CODE REVIEW

**Comment by adborden** [comment]
~@FuhuXia please create a release branch as described on the [wiki](https://github.com/GSA/datagov-deploy/wiki/Releases#create-the-release-pr). If anyone merges changes to `develop`, between deploying to sandbox and production, you won't be testing the same changes. It's important to create the release branch so you don't hold up development.~

**Comment by adborden** [comment]
Oops, sorry, I was reading your description mentioning `develop`. The branch is correct :+1:

**Comment by adborden** [comment]
@FuhuXia there is a fix for Snyk as part of https://github.com/GSA/datagov-deploy/pull/1474. This branch also includes fixes to sandbox, so I think it is worth pulling into the release branch.

**Comment by jbrown-xentity** [comment]
@adborden :+1: #1474 pulled in.

**Comment by FuhuXia** [comment]
successfully deployed to staging.

**Review by jbrown-xentity — APPROVED** [review]

**Pull request merged**
