### PR TITLE
[hotfix] create a separate key for sandbox environment

### PR DESCRIPTION
**Pull request by adborden**
https://github.com/GSA/datagov-deploy/issues/1560

This creates a new sandbox vault containing all the vault files in the sandbox inventory.

This will break developer workflows who are attempting to view/edit sandbox secrets. Developers should follow the recently updated [vault instructions](https://github.com/GSA/datagov-deploy/#ansible-vault) to get setup with the new sandbox key.

### CODE REVIEW

**Comment by FuhuXia** [comment]
Verified vault is working after add new sandbox secret file.

**Review by jbrown-xentity — APPROVED** [review]
Confirmed access to various files using latest readme updates, all accessible.

**Comment by adborden** [comment]
Updated the [vault rekeying instructions](https://github.com/GSA/datagov-deploy/wiki/Keypair-Rotation#ansible-vault).

**Comment by adborden** [comment]
🤦 so I don't quite have a handle on this. Even though ansible/group_vars/all/vault.yml is encrypted with the production vault label, running the playbooks in sandbox still want to read it and fail. [AFAICT](https://docs.ansible.com/ansible/latest/user_guide/vault.html), you can't encrypt a single file with multiple vaults... so I think this means we have to get rid of ansible/group_vars/all/vault.yml. I think that's okay, but could use a pair to come up with an alternative.

**Comment by jbrown-xentity** [comment]
This file was already a bit of an anti-pattern since we had to put in the key twice for the different environments, so maybe we just put them in the relevant inventories vault file? Would that require us to put them in both the staging and production vaults? Happy to :pear: sometime today or tomorrow...

**Comment by adborden** [comment]
> This file was already a bit of an anti-pattern since we had to put in the key twice for the different environments, so maybe we just put them in the relevant inventories vault file? Would that require us to put them in both the staging and production vaults? Happy to  sometime today or tomorrow...

Right, if we did that, we'd actually have to add an operator key 4 times (production, staging, mgmt, sandbox). Trying to keep it down to two.

**Comment by adborden** [comment]
Chatted with @jbrown-xentity and @FuhuXia last week on this. We should remove `ansible/group_vars/all/vault.yml` altogether.

**Comment by adborden** [comment]
Replaced by https://github.com/GSA/datagov-deploy/pull/1928

**Pull request closed without merging**
