### PR TITLE
Update plugins and ini file

### PR DESCRIPTION
**Pull request by avdata99**
- Updated for new extensions added
 - Updated INI file for DataGovTheme new settings

### CODE REVIEW

**Review by adborden — APPROVED** [review]

**Comment by woodt** [comment]
This is great, thanks!  Only question I have is whether we really want the datastore and datapusher turned on.

**Comment by adborden** [comment]
No, my understanding is that datastore/datapusher are not necessary for catalog as a metadata store. It would only be useful if we were storing datasets (and we are not). datastore/datapusher are not enabled on catalog.data.gov today (but are used for inventory.data.gov).

**Review by woodt — APPROVED** [review]
Approved.

**Comment by avdata99** [comment]
Removed datastore and datapusher

**Pull request merged**
