### PR TITLE
[Review] 1016

### PR DESCRIPTION
**Pull request by ydave-reisys**
- Made Updates for catalog vagrant setup

### CODE REVIEW

**Comment by ydave-reisys** [comment]
This is ready for review.

**Review by adborden — CHANGES_REQUESTED** [review]
@ydave-reisys can you split out the Vagrant changes to a separate PR?

The SSH change is a special case where we should branch off of master and treat the change like a hotfix. That way the SSH key change can be applied immediately, rather than waiting for the sprint release.

**Comment by ydave-reisys** [comment]
created separate PR for key update 
https://github.com/GSA/datagov-deploy/pull/1179

**Comment by adborden** [comment]
Thanks @ydave-reisys I'm going to try this locally and make a few tweaks.

**Comment by mogul** [comment]
@adborden this one's getting stale... What do you want to do with it?

**Comment by mogul** [comment]
> @adborden this one's getting stale... What do you want to do with it?

**Comment by mogul** [comment]
Closing the PR but explicitly leaving the branch for future reference if we need to do more work inside Vagrant.

**Pull request closed without merging**
