### PR TITLE
Add feature template

### PR DESCRIPTION
**Pull request by mogul**

### CODE REVIEW

**Comment by adborden** [comment]
I think you want this on the `develop` branch which is still the default for this repo. I think that's where GH will pull the templates from.

**Comment by mogul** [comment]
Rebased... Give it another look?

**Review by adborden — APPROVED** [review]

**Comment by adborden** [comment]
Feature === Epic ?

**Comment by mogul** [comment]
"Epic" is generic and overloaded terminology basically meaning "a clump of smaller related stories". I use "Feature" specifically to refer to those Epics that we want to track at the program level, eg on a roadmap or timeline, and in a separate prioritized backlog.

**Comment by mogul** [comment]
Any insight into the CircleCI failure here, @adborden ?

**Comment by adborden** [comment]
I think you need to rebase/merge `develop` to pull in the CI fix.

**Pull request merged**
