### PR TITLE
Update vault.yml

### PR DESCRIPTION
**Pull request by pjsharpe07**
Added my vault key

### CODE REVIEW

**Review by mogul — CHANGES_REQUESTED** [review]
When I run `ansible-vault view ansible/group_vars/all/vault.yml` I get 

```
[WARNING]: There was a vault format error in ansible/group_vars/all/vault.yml: Vault format unhexlify error: Non-hexadecimal digit found

ERROR! Vault format unhexlify error: Non-hexadecimal digit found for ansible/group_vars/all/vault.yml
```

That doesn't happen on the parent commit so I think this commit is corrupting the vault. Can you try remaking your change and double-checking with `ansible-vault view` before committing?

**Comment by jbrown-xentity** [comment]
@mogul where do we stand on this issue? Can it be merged?

**Comment by adborden** [comment]
The vault file looks fixed (works with `ansible-vault view`), but @jbrown-xentity and @pjsharpe07 's entries are missing the `active: true` flag, so your access will be removed by this PR.

**Comment by jbrown-xentity** [comment]
Should be fixed now, thanks

**Review by adborden — APPROVED** [review]

**Comment by adborden** [comment]
Looks good to me. I think @mogul still needs to dismiss the Change Requested, and you'll need to rebase or merge in the latest  develop to pick up the CI fix.

**Review by mogul — APPROVED** [review]

**Comment by adborden** [comment]
Looks like the merge didn't work. There are duplicate commits in here. Do you mind cleaning it up? Grab me if you need a pair.

Screenshot from 2020-02-12 13-11-00

**Pull request closed without merging**
