### PR TITLE
[hotfix] Saml2 0.4.0 who.ini

### PR DESCRIPTION
**Pull request by starsinmypockets**
Before merging
- [ ] Confirm Service Provider metadata has been updated with MAX.gov
- [ ] https://github.com/GSA/catalog-app/pull/133

On deploy, make sure to set the `force_rebuild_python=1` variable to trigger a python rebuild with the updated libgdbm-dev bindings.

    $ ansible-playbook site.yml -e force_python_rebuild=1 --limit catalog-web-v1

### CODE REVIEW

**Comment by adborden** [comment]
Part of https://github.com/GSA/datagov-ckan-multi/issues/346

**Comment by adborden** [comment]
@starsinmypockets can you rebase this onto `master`? Since it's tied to MAX.gov and a change in [catalog-app](https://github.com/GSA/catalog-app/pull/133), we'll want to plan to roll this out as a hotfix, separate from our normal release process.

**Review by woodt — APPROVED** [review]
This looks correct to me!  Nice.

**Comment by adborden** [comment]
@starsinmypockets this looks 👍 to me. I'm going to convert it to draft to avoid merging before we have confirmation from MAX.gov. I think you'll also want to update this PR once https://github.com/GSA/datagov-deploy-common/pull/50 is merged to bump the gsa.datagov-deploy-common role version.

**Comment by adborden** [comment]
@starsinmypockets just a reminder to document the ansible command we can use to deploy the right branches for testing this before we put this down.

**Comment by adborden** [comment]
From @starsinmypockets this was the command used in staging
`pipenv run ansible-playbook common.yml -e '{"rebuild_python":"true"}' -i inventories/sandbox -l v1`

**Comment by avdata99** [comment]
Closing since most code here was already added by @woodt [here](https://github.com/GSA/datagov-deploy/commit/c56dbd558aaae40a1227d494b6b00f229b99d09b) and saml2 is ~working fine

**Pull request closed without merging**
