### PR TITLE
Add management jumpbox details

### PR DESCRIPTION
**Pull request by mogul**

### CODE REVIEW

**Review by ydave-reisys — CHANGES_REQUESTED** [review]
Management Host is datagovjumpbox1m.mgmt-ocsit.bsp.gsa.gov

**Comment by adborden** [comment]
@ydave-reisys I've assigned this issue to you. Please make that change directly.

**Comment by ydave-reisys** [comment]
@adborden Changes made.

**Comment by adborden** [comment]
Thanks, can you update the [hosts](https://github.com/GSA/datagov-deploy/blob/develop/ansible/inventories/mgmt/hosts#L4) file as well?

**Comment by adborden** [comment]
@ydave-reisys isn't it `datagovjump1m.mgmt-ocsit.bsp.gsa.gov` and not `datagovjumpbox1m.mgmt-ocsit.bsp.gsa.gov`?

**Review by ydave-reisys — APPROVED** [review]

**Pull request merged**
