### PR TITLE
Replace beats role with upstream

### PR DESCRIPTION
**Pull request by adborden**
gsa.datagov-deploy-common was already updated with this change, but we forgot to
make it in our requirements.yml.

### CODE REVIEW

**Review by jbrown-xentity — APPROVED** [review]
The linter doesn't like the formatting, but I think it's fine and matches the other entries in the file... @adborden leaving for you to edit or merge as is.

**Comment by adborden** [comment]
The linting is failing here because it's looking for the `gsa.ansible-role-beats` role which was just removed. The issue is I forgot to bump `gsa.datagov-deploy-common` to [v3.0.0](https://github.com/GSA/datagov-deploy-common/releases/tag/v3.0.0) which swaps `gsa.ansible-role-beats` for `jobscore.beats`.

**Comment by adborden** [comment]
Rebased to pick up CI fix and added the missing version bump.

**Comment by adborden** [comment]
Rebased to resolve merge contflict.

**Pull request merged**
