### PR TITLE
Update DNS names

### PR DESCRIPTION
**Pull request by adborden**
https://github.com/GSA/datagov-ckan-multi/issues/298

- Add -next names for catalog and inventory (catalog-next.data.gov is already in this list).
- Add ci.data.gov for Jenkins
- Staging SANs

### CODE REVIEW

**Comment by adborden** [comment]
Oops, had some extra commits in there. I added SANs for the staging host names, we've never generated certs for them before using our [process](https://github.com/GSA/datagov-deploy/wiki/TLS-SSL-Certificates).

**Comment by adborden** [comment]
The staging SANs cover https://github.com/GSA/datagov-ckan-multi/issues/296

**Review by FuhuXia — APPROVED** [review]

**Comment by FuhuXia** [comment]
@adborden Does this require new certs to be generated and installed on BSP and sandbox aws?

**Comment by adborden** [comment]
>  Does this require new certs to be generated and installed on BSP and sandbox aws?

Yes, it does. I've already submitted a ~story~ Service Now ticket for creating the staging cert in https://github.com/GSA/datagov-ckan-multi/issues/296. Production will fall under https://github.com/GSA/datagov-ckan-multi/issues/298.

**Pull request merged**
