### PR TITLE
Rekey the ansible vault secret 

### PR DESCRIPTION
**Pull request by mogul**
The new key is available in the [shared team drive](https://docs.google.com/document/d/1detdsnIuwmqz6asrIfUWrmxCr56MGschY1yV0UeC_24/edit). Verify that you're able to view/edit this content using `ansible-vault view` before merging this PR.

### CODE REVIEW

**Comment by FuhuXia** [comment]
verified. the changed file can be viewed with new vault key.

**Review by FuhuXia — APPROVED** [review]

**Comment by mogul** [comment]
Addresses #1513

**Comment by adborden** [comment]
Yeah, I think updating the README to link to the vault secret is a good idea.

**Comment by mogul** [comment]
OK, I think I hit all references to it. Waiting for tests to pass then will merge.

**Pull request merged**
