### PR TITLE
Release/20191129

### PR DESCRIPTION
**Pull request by adborden**

### CODE REVIEW

**Comment by adborden** [comment]
No changes for sdg.

**Comment by adborden** [comment]
I was able to roll this out on staging successfully. I'll do it once more when all the application PRs are merged.

**Comment by adborden** [comment]
Successfully deployed to staging.

**Review by mogul — APPROVED** [review]

**Comment by adborden** [comment]
Deployed to production.
```
real    129m16.395s
user    32m45.444s
sys     15m1.467s
```

**Comment by adborden** [comment]
No changes required for `develop` merge.

**Pull request merged**
