### PR TITLE
Bump the java version in use

### PR DESCRIPTION
**Pull request by mogul**

### CODE REVIEW

**Review by adborden — APPROVED** [review]

**Comment by adborden** [comment]
The CI error was fixed on develop, @mogul you should update the branch when ready (either merge or rebase).

**Review by adborden — APPROVED** [review]

**Comment by adborden** [comment]
Oh, did you rebase the php-common fix? It shouldn't be showing up in this branch since it's already on develop. Sometimes this can cause merge conflicts and it will show up as duplicate commits. This is one of the risks of rebasing. Happy to chat more.

**Comment by adborden** [comment]
... oh, but doing the reverse would be fine, rebasing this branch on develop (fixed) would pick up the change without rewriting any history.

**Comment by mogul** [comment]
I _think_ I did that right... Just waiting for tests now.

**Comment by adborden** [comment]
👍 one commit, looks much better.

**Pull request merged**
