### PR TITLE
Remove unused role

### PR DESCRIPTION
**Pull request by adborden**
software/catalog/nginx isn't used anywhere.

### CODE REVIEW

**Comment by adborden** [comment]
Oops, I guess it's used in web-proxy.yml. @JJediny is that used for anything? I don't think it is.

**Review by JJediny — CHANGES_REQUESTED** [review]
The nginx proxy is used to proxy pycsw to `/csw` on catalog.data.gov it was never fully implemented

**Comment by adborden** [comment]
Let's dig into this a little more. I think apache is handling the [proxying to pycsw](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/catalog/ckan-app/templates/etc/apache2/sites-enabled/ckan.default.conf.j2#L14). It looks like nginx isn't installed on the production catalog-web hosts.

**Comment by adborden** [comment]
Discussed offline, Apache is currently handling the proxy. Nginx was never implemented, so we're going to go ahead and remove web-proxy.yml.

**Review by JJediny — APPROVED** [review]

**Comment by adborden** [comment]
Removed web-proxy playbook.

**Pull request merged**
