### PR TITLE
Continuous delivery to sandbox

### PR DESCRIPTION
**Pull request by adborden**
https://github.com/GSA/datagov-deploy/issues/1519

Piggy-backing on https://github.com/GSA/datagov-ckan-multi/issues/287

Enables the CircleCI -> Jenkins deployment job.

### CODE REVIEW

**Review by mogul — APPROVED** [review]
Note that this will need to merge in the snyk-snoozing PR before snyk-test passes!

**Comment by mogul** [comment]
Oh, but I guess Snyk isn't a requirement for merging the PR, so I'll go ahead with that.

**Comment by Valecia2023** [comment]
4fcbea9350b7b56379408d61696b356b9ee6856b

**Review by Valecia2023 — COMMENTED** [review]
4fcbea9350b7b56379408d61696b356b9ee6856b

**Pull request merged**
