### PR TITLE
[jumpbox] move jumpbox_operators to vault

### PR DESCRIPTION
**Pull request by adborden**
Since they contain personal work email addresses, they should be considered
secret.

### CODE REVIEW

**Comment by adborden** [comment]
@JJediny I don't have the ansible vault key for mgmt. Can you send me the key or add the operators variable?

**Comment by adborden** [comment]
Let's go ahead with this as-is. @JJediny can you review?

**Comment by adborden** [comment]
Rebased to resolve conflicts.

**Review by JJediny — APPROVED** [review]
LGTM

**Pull request merged**
